server:
  servlet:
    context-path: /community

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/community?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    #            username: yanfuyou
#    username: ENC(S//rh+y/XrH6g4GXGEdvFQ==)
    username: yanfuyou
    #            password: d40131522f6ee578
#    password: ENC(S//rh+y/XrH6g4GXGEdvFQ==)
    password: d40131522f6ee578
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10 #初始化时建立物理连接的个数
      min-idle: 0 #最小连接池数量
      maxActive: 100 #最大连接池数量
      maxWait: 20000 #获取连接时最大等待时间，单位毫秒
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      time-between-eviction-runs-millis: 20000 #既作为检测的间隔时间又作为test-while-idle执行的依据
      min-evictable-idle-time-millis: 30000 #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      #用来检测连接是否有效的sql
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: SELECT 'x'
      test-on-borrow: false #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      exception-sorter: true #当数据库抛出不可恢复的异常时,抛弃该连接
      pool-prepared-statements: true #是否缓存preparedStatement,mysql5.5+建议开启
      max-pool-prepared-statement-per-connection-size: 20 #当值大于20时poolPreparedStatements会自动修改为true
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
      #filters通过别名的方式配置扩展插件，常用的插件有：
      #监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
      filters: stat,wall,log4j
      # 配置 DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      stat-view-servlet:
        enable: true
        url-pattern: /druid/*
        # 禁用 HTML 中 Reset All 按钮
        reset-enable: false
        # 登录用户名/密码
        login-username: root
        login-password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  redis:
    #    主机地址
    host: 127.0.0.1
    #    端口
    port: 6379
#    密码
    password: ENC(AsYtJ2MfsAOLgb4hyICdGQ==)
    #    数据库索引（默认为0）
    database: 0
    #    连接超时时间
    timeout: 1800000
    lettuce:
      pool:
        #        最大连接数
        max-active: 20
        #        最大等待阻塞时间
        max-wait: -1
        #        最大空闲连接数
        max-idle: 5
        #        最小空闲连接数
        min-idle: 0
    #        TODO 需要配置集群节点信息,如果使用了集群

logging:
  config: classpath:logback-spring.xml
  level:
    root: info

jasypt:
  encryptor:
    password: fuyou20220909
#sa-token配置
sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 2592000
  activity-timeout: 3600
#  是否允许同时登录
  is-concurrent: false
#  同时登录是否共用一个token
  is-share: false
  token-style: simple-uuid
#  是否打印操作日志
#  is-log: true
#  不使用cookie
  is-read-cookie: false
  is-print: false

community:
  fileHost: http://192.168.3.7
swagger:
  enable: false

#  忽略拦截目录
not-match-path:
  path-list:
    - /user/login
    - /user/signup
    - /favicon.ico
    - /code/num
    - /article/miniList
    - /material/list
    - /user/userMini
    - /file/videoList
    - /article/getHots/**
    - /material/downloadCount
    - /hole/page
    - /team/list
    - /upload/files/**
    - /article/search
    - /sys/label/getSysLabels
    - /article/getArticleInfo/**
    - /article/readPlusOne/**
    - /user/**
    - /comment/getCommentTree/**
    - /material/myMaterial/**
    - /collect/page
    - /team/getMyTeam/**
    - /article/enclInfo/**
    - /userArt/getReport/**
    - /upload/**
    - /druid/**