server:
  servlet:
    context-path: /community

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10 #初始化时建立物理连接的个数
      min-idle: 5 #最小连接池数量
      maxActive: 100 #最大连接池数量
      maxWait: 20000 #获取连接时最大等待时间，单位毫秒
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      time-between-eviction-runs-millis: 20000 #既作为检测的间隔时间又作为test-while-idle执行的依据
      min-evictable-idle-time-millis: 30000 #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      #用来检测连接是否有效的sql
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: SELECT 'x'
      test-on-borrow: false #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      exception-sorter: true #当数据库抛出不可恢复的异常时,抛弃该连接
      pool-prepared-statements: true #是否缓存preparedStatement,mysql5.5+建议开启
      max-pool-prepared-statement-per-connection-size: 20 #当值大于20时poolPreparedStatements会自动修改为true
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
      #filters通过别名的方式配置扩展插件，常用的插件有：
      #监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
      filters: stat,wall,log4j

    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://mysql.sqlpub.com:3306/community?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
#          username: yanfuyou
          username: ENC(3ACEjPDauw5sPp7sOA6S5GlRtG5TguMx)
#          password: d40131522f6ee578
          password: ENC(n19liLUJvACUsf/Qg9vUhzN824lQcurmK+ps3/QHmKI=)
          driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  config: classpath:logback-spring.xml
  level:
    root: info

jasypt:
  encryptor:
    password: fuyou20220909